name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH and deploy to Hostinger
        run: |
          # Set variables
          SSH_HOST=145.223.106.133
          SSH_PORT=65002
          SSH_USER=u522518288
          SSH_DIR=/home/u522518288/domains/dandsinvestment.com/public_html

          # Create .ssh directory
          mkdir -p ~/.ssh

          # Add Hostinger's known host key
          echo "$SSH_HOST ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDhgZJSTvfoiUUxq+06BdvqpzAGyx/3eUCaTIQLgBKFZ jondesserres@gmail.com" > ~/.ssh/known_hosts

          # Set up SSH private key
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

          # Start SSH agent and add the SSH private key
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_ed25519

          # Test SSH connection to Hostinger
          ssh -vvv -o StrictHostKeyChecking=no -p $SSH_PORT $SSH_USER@$SSH_HOST "echo 'SSH connection successful'"

          # Deploy to Hostinger
          ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "
            cd $SSH_DIR &&
            echo 'Current branch:' &&
            git branch &&
            git status &&
            git pull origin master &&
            echo 'Pull completed, current status:' &&
            git status
          "

      - name: Clean up
        if: always()
        run: |
          rm -f ~/.ssh/id_ed25519
          rm -f ~/.ssh/known_hosts
