name: Deploy to Hostinger

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .ssh directory and add SSH host key
        run: |
          mkdir -p ~/.ssh
          echo "149.100.151.13 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDhgZJSTvfoiUUxq+06BdvqpzAGyx/3eUCaTIQLgBKFZ jondesserres@gmail.com" >> ~/.ssh/known_hosts
        shell: /usr/bin/bash -e {0}

      - name: Set up SSH private key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "Private key successfully written"

      - name: Start SSH agent and add key
        run: |
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_ed25519
          export SSH_AUTH_SOCK=$SSH_AUTH_SOCK
          echo "SSH key added to agent."
          ssh-add -l || echo "No SSH keys added."

      - name: Verify SSH key setup
        run: |
          ls -la ~/.ssh
          ssh-add -l || echo "No keys in SSH agent."

      - name: Test SSH connection to GitHub
        run: |
          ssh -T git@github.com || echo "Failed to connect to GitHub"
      
      - name: Test SSH connection to Hostinger
        run: |
          ssh -vvv -o StrictHostKeyChecking=no -p 65002 u522518288@149.100.151.13 'echo "SSH connection successful"'

      - name: Deploy to Hostinger
        run: |
          ssh -p 65002 u522518288@149.100.151.13 "
            cd /home/u522518288/domains/dandsinvestment.com/public_html &&
            git stash || true &&
            git pull origin master || { echo 'Failed to pull changes. Check for conflicts.'; exit 1; } &&
            git stash pop || echo 'No stashed changes to pop.'"

      - name: Clean up SSH keys
        if: always()
        run: |
          rm -f ~/.ssh/id_ed25519
          rm -f ~/.ssh/known_hosts
        shell: /usr/bin/bash -e {0}